/**
 * Copyright (c) 2016 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

#include "HvContext_SynthTest2.h"
#include "HvMath.h"



/*
 * Function Declarations
 */
static void cBinop_9Ewcv_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_WsEre_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_mRs3U_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_dZAWh_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_GMhD0_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_t6m5j_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_zNMJT_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_gONQ9_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_LPwKk_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_KBHxQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_iDmzu_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_4wz6J_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cCast_KKCYX_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_4td77_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_zFnGI_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_UOtED_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_FMi0K_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_Ifmh3_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_1enSB_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_sxvCT_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_nRYVY_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_lyTYh_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_L6iKW_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_M8zk2_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_eNOka_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_rurjL_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_4wHDG_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_cXDxm_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_2p7ka_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_Z4uuj_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_vXTml_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_M1Irq_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_74iUf_sendMessage(HvBase *, int, const HvMessage *const);
static void cIf_zRrco_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_XAz84_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_loD59_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_twF66_sendMessage(HvBase *, int, const HvMessage *const);
static void cIf_BOhRH_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_3lSD5_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_tJrTh_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_EdIGD_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_ebfug_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_iHbsc_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_PAbdN_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_UWwbF_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_9u2d5_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_m1Ym1_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_R4nFB_sendMessage(HvBase *, int, const HvMessage *const);
static void hTable_vyKNn_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_vY0nv_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_Mbbo5_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_xcJxZ_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_ObJZ2_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_AXLYk_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_htWSp_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_OKQeO_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_r8k1A_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_mavhz_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_q4r16_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_hL7Ys_sendMessage(HvBase *, int, const HvMessage *const);
static void sSample_AvCvp_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_uy3Gy_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_zkHsr_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_RzVqf_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_OEm52_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_JVBBg_sendMessage(HvBase *, int, const HvMessage *const);
static void hTable_xmCal_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_cstqU_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_WiCQA_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_fOSwr_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_ct2Mp_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_DUshp_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_3uYYS_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_n4V3J_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_FyLa0_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_7OZiz_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_KMbXu_sendMessage(HvBase *, int, const HvMessage *const);
static void cRandom_SHYml_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_6YxKK_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_6azFb_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_mvNhj_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_eZXmb_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_r6Lsv_sendMessage(HvBase *, int, const HvMessage *const);
static void sEnv_s7bY4_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_vGy9U_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_vUWHm_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_jT3ES_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_JZftf_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_3FiE4_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_v3Lpe_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_lP2S0_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_DyjCX_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cVar_8G3Lr_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_n8cea_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_5akK8_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_P4Kgr_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_GvXJS_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_dJoyc_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_HAUPZ_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_5tRR9_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_1Us8X_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_ORtkF_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_gbAPz_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_fuQqj_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_4Q5FZ_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_rOLqd_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_npZ9j_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_8uxdy_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_GxDbI_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_I205j_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_hSppS_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_0BVnY_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_ahKMK_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_UDLMy_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_9BQIb_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_DzaW9_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_AR1TX_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_eAbE0_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_vO95I_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cMsg_EKkpu_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_7XFpp_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_Zkj9O_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_3IKrB_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_0ysuM_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_X2XBC_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_aMvev_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_5syzx_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_wnI6j_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_7JeuE_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_JxbWD_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_AKOn8_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_rCJWT_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_UYb1p_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_yjGQ8_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_CWVi9_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_0Lt2o_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_gVVJ1_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_Y6WEt_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_Kw5MX_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_N1NtC_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_sPFol_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_TIELF_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_DXAZA_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_reXrp_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_1tEu8_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_CwMiQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_MNrLL_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_DPDmU_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_98zVJ_sendMessage(HvBase *, int, const HvMessage *const);
static void sSample_MLbfG_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_3e3Tf_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_3vk6k_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_JdRHQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_EOjbQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_fKj2r_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_jRH83_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_01Y7t_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_yeNz2_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_vGVsK_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_5MbUt_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_7exOa_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_lBTZN_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_QPmnz_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_C3ryy_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_03gmg_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_t6LXT_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_xfSll_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(
    HvBase *const _c, hv_uint32_t receiverHash, HvMessage *m) {
  switch (receiverHash) {
    case 0xEDDCC518: { // delayTime
      ctx_scheduleMessage(_c, m, &cReceive_dZAWh_sendMessage, 0);
      break;
    }
    case 0xA822F34D: { // dryWet
      ctx_scheduleMessage(_c, m, &cReceive_C3ryy_sendMessage, 0);
      break;
    }
    case 0xF1E7CD16: { // feedback
      ctx_scheduleMessage(_c, m, &cReceive_mavhz_sendMessage, 0);
      break;
    }
    case 0xF1E5B1C5: { // grainSize
      ctx_scheduleMessage(_c, m, &cReceive_01Y7t_sendMessage, 0);
      break;
    }
    case 0x566BEAF1: { // lfoAmp
      ctx_scheduleMessage(_c, m, &cReceive_1Us8X_sendMessage, 0);
      break;
    }
    case 0x163690BB: { // lfoFreq
      ctx_scheduleMessage(_c, m, &cReceive_lBTZN_sendMessage, 0);
      break;
    }
    case 0xC1312B53: { // lfoToggle
      ctx_scheduleMessage(_c, m, &cReceive_HAUPZ_sendMessage, 0);
      break;
    }
    case 0x38196801: { // oscAmp
      ctx_scheduleMessage(_c, m, &cReceive_5tRR9_sendMessage, 0);
      break;
    }
    case 0x204E6574: { // oscFreq
      ctx_scheduleMessage(_c, m, &cReceive_v3Lpe_sendMessage, 0);
      break;
    }
    case 0x8B2148DD: { // pitch
      ctx_scheduleMessage(_c, m, &cReceive_fuQqj_sendMessage, 0);
      break;
    }
    case 0xF54ACBD: { // randPitch
      ctx_scheduleMessage(_c, m, &cReceive_r8k1A_sendMessage, 0);
      break;
    }
    case 0xBEFE14EE: { // sourceSwitch
      ctx_scheduleMessage(_c, m, &cReceive_vGVsK_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    case 0xE9D577FE: return &Context(_c)->hTable_vyKNn; // del-b1
    case 0x53B53393: return &Context(_c)->hTable_xmCal; // del-d1
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

#ifdef __cplusplus
extern "C" {
#endif
HV_EXPORT Hv_SynthTest2 *hv_SynthTest2_new_with_options(double sampleRate, int poolKb) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  hv_assert(poolKb >= 1); // a message pool of some reasonable size is always needed
  Hv_SynthTest2 *const _c = (Hv_SynthTest2 *) hv_malloc(sizeof(Hv_SynthTest2));
  hv_assert(_c != NULL);

  Base(_c)->numInputChannels = 2;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "SynthTest2";

  hLp_init(&Base(_c)->msgPipe, 1024);
  Base(_c)->msgLock = false;

  Base(_c)->numBytes = sizeof(Hv_SynthTest2);
  Base(_c)->numBytes += mq_initWithPoolSize(&Base(_c)->mq, poolKb);
  Base(_c)->numBytes += sTabhead_init(&_c->sTabhead_doIRc, &_c->hTable_xmCal);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_fpV6w, &_c->hTable_xmCal, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_3wyaX, &_c->hTable_xmCal, false);
  Base(_c)->numBytes += sEnv_init(&_c->sEnv_s7bY4, 1024, 512);
  Base(_c)->numBytes += sSample_init(&_c->sSample_AvCvp);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_YEUi9, 0.0f, sampleRate);
  Base(_c)->numBytes += sDel1_init(&_c->sDel1_aqZsP);
  Base(_c)->numBytes += sSamphold_init(&_c->sSamphold_muJf8);
  Base(_c)->numBytes += sTabhead_init(&_c->sTabhead_Is7NT, &_c->hTable_vyKNn);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_tWIk8, &_c->hTable_vyKNn, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_4ceK8, &_c->hTable_vyKNn, false);
  Base(_c)->numBytes += sDel1_init(&_c->sDel1_rL8gP);
  Base(_c)->numBytes += sSamphold_init(&_c->sSamphold_q1Nbj);
  Base(_c)->numBytes += sTabhead_init(&_c->sTabhead_80SR0, &_c->hTable_vyKNn);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_bGNc4, &_c->hTable_vyKNn, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_GcFjQ, &_c->hTable_vyKNn, false);
  Base(_c)->numBytes += sTabwrite_init(&_c->sTabwrite_JGG4s, &_c->hTable_vyKNn);
  Base(_c)->numBytes += sTabwrite_init(&_c->sTabwrite_3Q7Hv, &_c->hTable_xmCal);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_ovvF6, 0.0f, sampleRate);
  Base(_c)->numBytes += sSample_init(&_c->sSample_MLbfG);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_IlhaM, 0.0f, sampleRate);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_WsEre, 0.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_mRs3U, 1.0f); // __mul
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_zNMJT, 0.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_LPwKk, 0.0f); // __mul
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_KBHxQ, 10.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_S6eRd, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_s(&_c->cVar_lyTYh, "del-b1");
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_dkjNR, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_MlZog, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_4wHDG, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_2p7ka, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_Z4uuj, 2.0f);
  Base(_c)->numBytes += cIf_init(&_c->cIf_zRrco, true);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_twF66, 44100.0f);
  Base(_c)->numBytes += cIf_init(&_c->cIf_BOhRH, true);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_EdIGD, 0.0f);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_m1Ym1, 0.0f);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_R4nFB, 0.0f);
  Base(_c)->numBytes += hTable_init(&_c->hTable_vyKNn, 256);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_AXLYk, 1.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_q4r16, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_uy3Gy, 0.0f);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_RzVqf, 0.0f);
  Base(_c)->numBytes += hTable_init(&_c->hTable_xmCal, 256);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_cstqU, 0.0f);
  Base(_c)->numBytes += sVari_init(&_c->sVari_eKbc2, 0, 0, false);
  Base(_c)->numBytes += cRandom_init(&_c->cRandom_SHYml, -639666865);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_mvNhj, 0.0f); // __add
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_DTI7M, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_eZXmb, 0.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_r6Lsv, 0.0f); // __div
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_vUWHm, 440.0f); // __add
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_jT3ES, 0.0f); // __pow
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_3FiE4, 200.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_ZP6wX, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_Km8h8, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_8G3Lr, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_n8cea, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_5akK8, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_GvXJS, 0.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_WOTlu, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_vu7ud, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_gbAPz, 0.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_QtaNJ, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_4Q5FZ, 1.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_npZ9j, 1.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_GxDbI, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_I205j, 0.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_ahKMK, 0.0f); // __mul
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_UDLMy, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_7XFpp, 100.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_3IKrB, 1.0f); // __mul
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_X2XBC, 0.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_YAYce, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_s(&_c->cVar_wnI6j, "del-b1");
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_AMGmd, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_XKa0f, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_oCVD3, 0.6f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_KRwMf, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_s(&_c->cVar_reXrp, "del-d1");
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_xABvP, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_gGFUT, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_CwMiQ, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_MNrLL, 0.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_ry7CS, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_JdRHQ, 0.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_EhxvV, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_EOjbQ, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_fKj2r, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_jRH83, 100.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_QPmnz, 0.0f);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_wEdqT, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_Ag72Y, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_03gmg, 0.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_t6LXT, 1.0f); // __mul

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_gONQ9_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_WiCQA_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_eAbE0_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_6azFb_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_xcJxZ_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_3e3Tf_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_7exOa_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_eNOka_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_JxbWD_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_Y6WEt_sendMessage, 0);

  return _c;
}

HV_EXPORT Hv_SynthTest2 *hv_SynthTest2_new(double sampleRate) {
  return hv_SynthTest2_new_with_options(sampleRate, 10); // default to 10KB MessagePool
}

HV_EXPORT void hv_SynthTest2_free(Hv_SynthTest2 *_c) {
  sEnv_free(&_c->sEnv_s7bY4);
  hTable_free(&_c->hTable_vyKNn);
  hTable_free(&_c->hTable_xmCal);

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled
  hLp_free(&Base(_c)->msgPipe);

  hv_free(_c);
}
#ifdef __cplusplus
}
#endif



/*
 * Static Function Implementation
 */
static void cBinop_9Ewcv_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_1tEu8_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_ORtkF_sendMessage);
}

static void cVar_WsEre_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_Km8h8, m);
}

static void cBinop_mRs3U_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_98zVJ_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_rurjL_sendMessage);
}

static void cReceive_dZAWh_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_I205j, 0, m, &cVar_I205j_sendMessage);
}

static void cCast_GMhD0_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 12.0f, 0, m, &cBinop_9Ewcv_sendMessage);
}

static void cBinop_t6m5j_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_LPwKk, HV_BINOP_MULTIPLY, 1, m, &cBinop_LPwKk_sendMessage);
}

static void cDelay_zNMJT_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_zNMJT, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_zNMJT, 0, m, &cDelay_zNMJT_sendMessage);
  sSample_onMessage(_c, &Context(_c)->sSample_MLbfG, 1, m);
}

static void cLoadbang_gONQ9_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_zFnGI_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_KBHxQ, 0, m, &cVar_KBHxQ_sendMessage);
}

static void cBinop_LPwKk_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MAX, 1.0f, 0, m, &cBinop_4td77_sendMessage);
}

static void cVar_KBHxQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_LPwKk, HV_BINOP_MULTIPLY, 0, m, &cBinop_LPwKk_sendMessage);
}

static void cMsg_iDmzu_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_zNMJT, 0, m, &cDelay_zNMJT_sendMessage);
}

static void cSwitchcase_4wz6J_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cMsg_iDmzu_sendMessage(_c, 0, m);
      break;
    }
    case 0x7A5B032D: { // "stop"
      cMsg_iDmzu_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_KKCYX_sendMessage);
      break;
    }
  }
}

static void cCast_KKCYX_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_iDmzu_sendMessage(_c, 0, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_zNMJT, 0, m, &cDelay_zNMJT_sendMessage);
  sSample_onMessage(_c, &Context(_c)->sSample_MLbfG, 1, m);
}

static void cBinop_4td77_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_zNMJT, 2, m, &cDelay_zNMJT_sendMessage);
}

static void cMsg_zFnGI_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_UOtED_sendMessage);
}

static void cSystem_UOtED_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_t6m5j_sendMessage);
}

static void cCast_FMi0K_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_JZftf_sendMessage(_c, 0, m);
}

static void cBinop_Ifmh3_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_S6eRd, m);
}

static void cMsg_1enSB_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_sxvCT_sendMessage);
}

static void cSystem_sxvCT_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_nRYVY_sendMessage);
}

static void cBinop_nRYVY_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_MlZog, m);
}

static void cVar_lyTYh_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_M8zk2_sendMessage(_c, 0, m);
}

static void cSystem_L6iKW_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 1.0f, 0, m, &cBinop_Ifmh3_sendMessage);
  sVarf_onMessage(_c, &Context(_c)->sVarf_dkjNR, m);
}

static void cMsg_M8zk2_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(3);
  msg_init(m, 3, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "table");
  msg_setElementToFrom(m, 1, n, 0);
  msg_setSymbol(m, 2, "size");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_L6iKW_sendMessage);
}

static void cLoadbang_eNOka_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_lyTYh, 0, m, &cVar_lyTYh_sendMessage);
  cMsg_1enSB_sendMessage(_c, 0, m);
}

static void cCast_rurjL_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_fKj2r, 0, m, &cVar_fKj2r_sendMessage);
}

static void cVar_4wHDG_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}

static void cCast_cXDxm_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_jRH83, 0, m, &cVar_jRH83_sendMessage);
}

static void cVar_2p7ka_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_cXDxm_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_3vk6k_sendMessage);
}

static void cVar_Z4uuj_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_GREATER_THAN, 0.0f, 0, m, &cBinop_M1Irq_sendMessage);
  cIf_onMessage(_c, &Context(_c)->cIf_zRrco, 0, m, &cIf_zRrco_sendMessage);
}

static void cUnop_vXTml_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_jT3ES, HV_BINOP_POW, 0, m, &cBinop_jT3ES_sendMessage);
}

static void cBinop_M1Irq_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cIf_onMessage(_c, &Context(_c)->cIf_zRrco, 1, m, &cIf_zRrco_sendMessage);
}

static void cUnop_74iUf_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_jT3ES, HV_BINOP_POW, 0, m, &cBinop_jT3ES_sendMessage);
}

static void cIf_zRrco_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cUnop_onMessage(_c, HV_UNOP_CEIL, m, &cUnop_74iUf_sendMessage);
      break;
    }
    case 1: {
      cUnop_onMessage(_c, HV_UNOP_FLOOR, m, &cUnop_vXTml_sendMessage);
      break;
    }
    default: return;
  }
}

static void cUnop_XAz84_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_X2XBC, 0, m, &cVar_X2XBC_sendMessage);
}

static void cUnop_loD59_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_r6Lsv, HV_BINOP_DIVIDE, 0, m, &cBinop_r6Lsv_sendMessage);
}

static void cVar_twF66_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_GREATER_THAN, 0.0f, 0, m, &cBinop_3lSD5_sendMessage);
  cIf_onMessage(_c, &Context(_c)->cIf_BOhRH, 0, m, &cIf_BOhRH_sendMessage);
}

static void cIf_BOhRH_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cUnop_onMessage(_c, HV_UNOP_CEIL, m, &cUnop_tJrTh_sendMessage);
      break;
    }
    case 1: {
      cUnop_onMessage(_c, HV_UNOP_FLOOR, m, &cUnop_loD59_sendMessage);
      break;
    }
    default: return;
  }
}

static void cBinop_3lSD5_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cIf_onMessage(_c, &Context(_c)->cIf_BOhRH, 1, m, &cIf_BOhRH_sendMessage);
}

static void cUnop_tJrTh_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_r6Lsv, HV_BINOP_DIVIDE, 0, m, &cBinop_r6Lsv_sendMessage);
}

static void cVar_EdIGD_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_3FiE4, 0, m, &cVar_3FiE4_sendMessage);
}

static void cMsg_ebfug_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "resize");
  msg_setElementToFrom(m, 1, n, 0);
  hTable_onMessage(_c, &Context(_c)->hTable_vyKNn, 0, m, &hTable_vyKNn_sendMessage);
}

static void cSystem_iHbsc_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_vY0nv_sendMessage);
}

static void cMsg_PAbdN_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_iHbsc_sendMessage);
}

static void cMsg_UWwbF_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "mirror");
  hTable_onMessage(_c, &Context(_c)->hTable_vyKNn, 0, m, &hTable_vyKNn_sendMessage);
}

static void cBinop_9u2d5_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_ebfug_sendMessage(_c, 0, m);
}

static void cDelay_m1Ym1_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_m1Ym1, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_R4nFB, 0, m, &cDelay_R4nFB_sendMessage);
  cDelay_onMessage(_c, &Context(_c)->cDelay_m1Ym1, 0, m, &cDelay_m1Ym1_sendMessage);
  sTabwrite_onMessage(_c, &Context(_c)->sTabwrite_JGG4s, 1, m, NULL);
}

static void cDelay_R4nFB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_R4nFB, m);
  cMsg_UWwbF_sendMessage(_c, 0, m);
}

static void hTable_vyKNn_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_ObJZ2_sendMessage(_c, 0, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_m1Ym1, 2, m, &cDelay_m1Ym1_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_Mbbo5_sendMessage);
}

static void cBinop_vY0nv_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 5000.0f, 0, m, &cBinop_9u2d5_sendMessage);
}

static void cCast_Mbbo5_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_m1Ym1, 0, m, &cDelay_m1Ym1_sendMessage);
}

static void cLoadbang_xcJxZ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_PAbdN_sendMessage(_c, 0, m);
}

static void cMsg_ObJZ2_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, (float) HV_N_SIMD);
  cDelay_onMessage(_c, &Context(_c)->cDelay_R4nFB, 2, m, &cDelay_R4nFB_sendMessage);
}

static void cVar_AXLYk_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_JdRHQ, 0, m, &cVar_JdRHQ_sendMessage);
}

static void cBinop_htWSp_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_GvXJS, 0, m, &cVar_GvXJS_sendMessage);
}

static void cBinop_OKQeO_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_t6LXT, HV_BINOP_MULTIPLY, 0, m, &cBinop_t6LXT_sendMessage);
}

static void cReceive_r8k1A_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_QPmnz, 0, m, &cVar_QPmnz_sendMessage);
}

static void cReceive_mavhz_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_8G3Lr, 0, m, &cVar_8G3Lr_sendMessage);
  cVar_onMessage(_c, &Context(_c)->cVar_uy3Gy, 0, m, &cVar_uy3Gy_sendMessage);
}

static void cVar_q4r16_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 1.0f, 0, m, &cBinop_hL7Ys_sendMessage);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, -1.0f, 0, m, &cBinop_CWVi9_sendMessage);
}

static void cBinop_hL7Ys_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cUnop_onMessage(_c, HV_UNOP_ABS, m, &cUnop_XAz84_sendMessage);
}

static void sSample_AvCvp_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_mRs3U, HV_BINOP_MULTIPLY, 0, m, &cBinop_mRs3U_sendMessage);
}

static void cVar_uy3Gy_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_DTI7M, m);
}

static void cMsg_zkHsr_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  cSwitchcase_vO95I_onMessage(_c, NULL, 0, m, NULL);
}

static void cDelay_RzVqf_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_RzVqf, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_cstqU, 0, m, &cDelay_cstqU_sendMessage);
  cDelay_onMessage(_c, &Context(_c)->cDelay_RzVqf, 0, m, &cDelay_RzVqf_sendMessage);
  sTabwrite_onMessage(_c, &Context(_c)->sTabwrite_3Q7Hv, 1, m, NULL);
}

static void cCast_OEm52_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_RzVqf, 0, m, &cDelay_RzVqf_sendMessage);
}

static void cBinop_JVBBg_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_ct2Mp_sendMessage(_c, 0, m);
}

static void hTable_xmCal_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_DUshp_sendMessage(_c, 0, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_RzVqf, 2, m, &cDelay_RzVqf_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_OEm52_sendMessage);
}

static void cDelay_cstqU_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_cstqU, m);
  cMsg_3uYYS_sendMessage(_c, 0, m);
}

static void cLoadbang_WiCQA_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_FyLa0_sendMessage(_c, 0, m);
}

static void cBinop_fOSwr_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 5000.0f, 0, m, &cBinop_JVBBg_sendMessage);
}

static void cMsg_ct2Mp_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "resize");
  msg_setElementToFrom(m, 1, n, 0);
  hTable_onMessage(_c, &Context(_c)->hTable_xmCal, 0, m, &hTable_xmCal_sendMessage);
}

static void cMsg_DUshp_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, (float) HV_N_SIMD);
  cDelay_onMessage(_c, &Context(_c)->cDelay_cstqU, 2, m, &cDelay_cstqU_sendMessage);
}

static void cMsg_3uYYS_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "mirror");
  hTable_onMessage(_c, &Context(_c)->hTable_xmCal, 0, m, &hTable_xmCal_sendMessage);
}

static void cSystem_n4V3J_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_fOSwr_sendMessage);
}

static void cMsg_FyLa0_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_n4V3J_sendMessage);
}

static void cMsg_7OZiz_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setElementToFrom(m, 0, n, 0);
  msg_setFloat(m, 1, 1.0f);
  sVari_onMessage(_c, &Context(_c)->sVari_eKbc2, m);
}

static void cUnop_KMbXu_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_7OZiz_sendMessage(_c, 0, m);
}

static void cRandom_SHYml_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 8388610.0f, 0, m, &cBinop_6YxKK_sendMessage);
}

static void cBinop_6YxKK_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cUnop_onMessage(_c, HV_UNOP_FLOOR, m, &cUnop_KMbXu_sendMessage);
}

static void cLoadbang_6azFb_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cRandom_onMessage(_c, &Context(_c)->cRandom_SHYml, 0, m, &cRandom_SHYml_sendMessage);
}

static void cBinop_mvNhj_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_0ysuM_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_dJoyc_sendMessage);
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_GMhD0_sendMessage);
}

static void cVar_eZXmb_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}

static void cBinop_r6Lsv_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_t6LXT, HV_BINOP_MULTIPLY, 1, m, &cBinop_t6LXT_sendMessage);
}

static void sEnv_s7bY4_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_4wHDG, 0, m, &cVar_4wHDG_sendMessage);
}

static void cCast_vGy9U_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_mRs3U, HV_BINOP_MULTIPLY, 1, m, &cBinop_mRs3U_sendMessage);
}

static void cBinop_vUWHm_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_n8cea, 0, m, &cVar_n8cea_sendMessage);
}

static void cBinop_jT3ES_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 1.0f, 0, m, &cBinop_OKQeO_sendMessage);
}

static void cMsg_JZftf_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.0f);
  cBinop_onMessage(_c, &Context(_c)->cBinop_vUWHm, HV_BINOP_ADD, 1, m, &cBinop_vUWHm_sendMessage);
}

static void cVar_3FiE4_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_vUWHm, HV_BINOP_ADD, 0, m, &cBinop_vUWHm_sendMessage);
}

static void cReceive_v3Lpe_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_3FiE4, 0, m, &cVar_3FiE4_sendMessage);
}

static void cCast_lP2S0_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_FMi0K_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_5MbUt_sendMessage);
}

static void cSwitchcase_DyjCX_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_lP2S0_sendMessage);
      break;
    }
    default: {
      break;
    }
  }
}

static void cVar_8G3Lr_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_ZP6wX, m);
}

static void cVar_n8cea_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_IlhaM, 0, m);
}

static void cVar_5akK8_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_3IKrB, HV_BINOP_MULTIPLY, 1, m, &cBinop_3IKrB_sendMessage);
}

static void cCast_P4Kgr_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_vUWHm, HV_BINOP_ADD, 1, m, &cBinop_vUWHm_sendMessage);
}

static void cVar_GvXJS_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_QtaNJ, m);
  sVarf_onMessage(_c, &Context(_c)->sVarf_Ag72Y, m);
}

static void cCast_dJoyc_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_twF66, 0, m, &cVar_twF66_sendMessage);
}

static void cReceive_HAUPZ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_npZ9j, 0, m, &cVar_npZ9j_sendMessage);
}

static void cReceive_5tRR9_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_oCVD3, m);
}

static void cReceive_1Us8X_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_3IKrB, HV_BINOP_MULTIPLY, 1, m, &cBinop_3IKrB_sendMessage);
}

static void cCast_ORtkF_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_Z4uuj, 0, m, &cVar_Z4uuj_sendMessage);
}

static void cVar_gbAPz_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}

static void cReceive_fuQqj_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_fKj2r, 0, m, &cVar_fKj2r_sendMessage);
}

static void cVar_4Q5FZ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_EQ, 0.0f, 0, m, &cBinop_rOLqd_sendMessage);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_EQ, 0.0f, 0, m, &cBinop_xfSll_sendMessage);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_EQ, 1.0f, 0, m, &cBinop_DPDmU_sendMessage);
}

static void cBinop_rOLqd_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_4Q5FZ, 1, m, &cVar_4Q5FZ_sendMessage);
}

static void cVar_npZ9j_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_EQ, 0.0f, 0, m, &cBinop_8uxdy_sendMessage);
  cSwitchcase_4wz6J_onMessage(_c, NULL, 0, m, NULL);
  cSwitchcase_DyjCX_onMessage(_c, NULL, 0, m, NULL);
}

static void cBinop_8uxdy_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_npZ9j, 1, m, &cVar_npZ9j_sendMessage);
}

static void cVar_GxDbI_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_QPmnz, 0, m, &cVar_QPmnz_sendMessage);
}

static void cVar_I205j_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}

static void cCast_hSppS_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_3FiE4, 0, m, &cVar_3FiE4_sendMessage);
}

static void cCast_0BVnY_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_EKkpu_sendMessage(_c, 0, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_UDLMy, 0, m, &cDelay_UDLMy_sendMessage);
  sSample_onMessage(_c, &Context(_c)->sSample_AvCvp, 1, m);
}

static void cBinop_ahKMK_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MAX, 1.0f, 0, m, &cBinop_Zkj9O_sendMessage);
}

static void cDelay_UDLMy_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_UDLMy, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_UDLMy, 0, m, &cDelay_UDLMy_sendMessage);
  sSample_onMessage(_c, &Context(_c)->sSample_AvCvp, 1, m);
}

static void cSystem_9BQIb_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_AR1TX_sendMessage);
}

static void cMsg_DzaW9_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_9BQIb_sendMessage);
}

static void cBinop_AR1TX_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_ahKMK, HV_BINOP_MULTIPLY, 1, m, &cBinop_ahKMK_sendMessage);
}

static void cLoadbang_eAbE0_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_DzaW9_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_7XFpp, 0, m, &cVar_7XFpp_sendMessage);
}

static void cSwitchcase_vO95I_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cMsg_EKkpu_sendMessage(_c, 0, m);
      break;
    }
    case 0x7A5B032D: { // "stop"
      cMsg_EKkpu_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_0BVnY_sendMessage);
      break;
    }
  }
}

static void cMsg_EKkpu_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_UDLMy, 0, m, &cDelay_UDLMy_sendMessage);
}

static void cVar_7XFpp_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_ahKMK, HV_BINOP_MULTIPLY, 0, m, &cBinop_ahKMK_sendMessage);
}

static void cBinop_Zkj9O_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_UDLMy, 2, m, &cDelay_UDLMy_sendMessage);
}

static void cBinop_3IKrB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_P4Kgr_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_hSppS_sendMessage);
}

static void cCast_0ysuM_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_jRH83, 0, m, &cVar_jRH83_sendMessage);
}

static void cVar_X2XBC_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_vu7ud, m);
}

static void cSystem_aMvev_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_UYb1p_sendMessage);
}

static void cMsg_5syzx_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_aMvev_sendMessage);
}

static void cVar_wnI6j_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_AKOn8_sendMessage(_c, 0, m);
}

static void cSystem_7JeuE_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 1.0f, 0, m, &cBinop_rCJWT_sendMessage);
  sVarf_onMessage(_c, &Context(_c)->sVarf_XKa0f, m);
}

static void cLoadbang_JxbWD_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_wnI6j, 0, m, &cVar_wnI6j_sendMessage);
  cMsg_5syzx_sendMessage(_c, 0, m);
}

static void cMsg_AKOn8_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(3);
  msg_init(m, 3, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "table");
  msg_setElementToFrom(m, 1, n, 0);
  msg_setSymbol(m, 2, "size");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_7JeuE_sendMessage);
}

static void cBinop_rCJWT_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_AMGmd, m);
}

static void cBinop_UYb1p_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_YAYce, m);
}

static void cUnop_yjGQ8_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_WsEre, 0, m, &cVar_WsEre_sendMessage);
}

static void cBinop_CWVi9_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cUnop_onMessage(_c, HV_UNOP_ABS, m, &cUnop_yjGQ8_sendMessage);
}

static void cMsg_0Lt2o_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  cVar_onMessage(_c, &Context(_c)->cVar_npZ9j, 0, m, &cVar_npZ9j_sendMessage);
}

static void cBinop_gVVJ1_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_KRwMf, m);
}

static void cLoadbang_Y6WEt_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_reXrp, 0, m, &cVar_reXrp_sendMessage);
  cMsg_TIELF_sendMessage(_c, 0, m);
}

static void cBinop_Kw5MX_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_gGFUT, m);
}

static void cMsg_N1NtC_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(3);
  msg_init(m, 3, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "table");
  msg_setElementToFrom(m, 1, n, 0);
  msg_setSymbol(m, 2, "size");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_DXAZA_sendMessage);
}

static void cSystem_sPFol_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_Kw5MX_sendMessage);
}

static void cMsg_TIELF_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_sPFol_sendMessage);
}

static void cSystem_DXAZA_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 1.0f, 0, m, &cBinop_gVVJ1_sendMessage);
  sVarf_onMessage(_c, &Context(_c)->sVarf_xABvP, m);
}

static void cVar_reXrp_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_N1NtC_sendMessage(_c, 0, m);
}

static void cCast_1tEu8_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_jT3ES, HV_BINOP_POW, 1, m, &cBinop_jT3ES_sendMessage);
}

static void cVar_CwMiQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_q4r16, 0, m, &cVar_q4r16_sendMessage);
  cVar_onMessage(_c, &Context(_c)->cVar_eZXmb, 0, m, &cVar_eZXmb_sendMessage);
}

static void cVar_MNrLL_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_2p7ka, 0, m, &cVar_2p7ka_sendMessage);
}

static void cBinop_DPDmU_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_ry7CS, m);
}

static void cCast_98zVJ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_mvNhj, HV_BINOP_ADD, 1, m, &cBinop_mvNhj_sendMessage);
}

static void sSample_MLbfG_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_3IKrB, HV_BINOP_MULTIPLY, 0, m, &cBinop_3IKrB_sendMessage);
}

static void cLoadbang_3e3Tf_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_zkHsr_sendMessage(_c, 0, m);
}

static void cCast_3vk6k_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_fKj2r, 0, m, &cVar_fKj2r_sendMessage);
}

static void cVar_JdRHQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_YEUi9, 0, m);
}

static void cVar_EOjbQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}

static void cVar_fKj2r_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_mvNhj, HV_BINOP_ADD, 0, m, &cBinop_mvNhj_sendMessage);
}

static void cVar_jRH83_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_r6Lsv, HV_BINOP_DIVIDE, 1, m, &cBinop_r6Lsv_sendMessage);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 44.1f, 0, m, &cBinop_htWSp_sendMessage);
}

static void cReceive_01Y7t_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_MNrLL, 0, m, &cVar_MNrLL_sendMessage);
}

static void cCast_yeNz2_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_mRs3U, HV_BINOP_MULTIPLY, 0, m, &cBinop_mRs3U_sendMessage);
}

static void cReceive_vGVsK_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_4Q5FZ, 0, m, &cVar_4Q5FZ_sendMessage);
}

static void cCast_5MbUt_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_3FiE4, 0, m, &cVar_3FiE4_sendMessage);
}

static void cLoadbang_7exOa_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_0Lt2o_sendMessage(_c, 0, m);
}

static void cReceive_lBTZN_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_ovvF6, 0, m);
}

static void cVar_QPmnz_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_vGy9U_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_yeNz2_sendMessage);
}

static void cReceive_C3ryy_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_CwMiQ, 0, m, &cVar_CwMiQ_sendMessage);
}

static void cVar_03gmg_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_ovvF6, 0, m);
}

static void cBinop_t6LXT_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_AXLYk, 0, m, &cVar_AXLYk_sendMessage);
}

static void cBinop_xfSll_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_EhxvV, m);
}




/*
 * Context Process Implementation
 */

#ifdef __cplusplus
extern "C" {
#endif
HV_EXPORT int hv_SynthTest2_process(Hv_SynthTest2 *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  while (hLp_hasData(&Base(_c)->msgPipe)) {
    hv_uint32_t numBytes = 0;
    ReceiverMessagePair *p = (ReceiverMessagePair *) hLp_getReadBuffer(&Base(_c)->msgPipe, &numBytes);
    hv_assert(numBytes >= sizeof(ReceiverMessagePair));
    ctx_scheduleMessageForReceiver(Base(_c), p->receiverHash, &p->msg);
    hLp_consume(&Base(_c)->msgPipe);
  }
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4, Bf5, Bf6, Bf7, Bf8, Bf9, Bf10;
  hv_bufferi_t Bi0, Bi1;

  // input and output vars
  hv_bufferf_t O0, O1;
  hv_bufferf_t I0, I1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    // load input buffers
    __hv_load_f(inputBuffers[0]+n, VOf(I0));
    __hv_load_f(inputBuffers[1]+n, VOf(I1));

    // zero output buffers
    __hv_zero_f(VOf(O0));
    __hv_zero_f(VOf(O1));

    // process all signal functions
    __hv_tabhead_f(&_c->sTabhead_doIRc, VOf(Bf0));
    __hv_var_k_f_r(VOf(Bf1), -1.0f, -2.0f, -3.0f, -4.0f, -5.0f, -6.0f, -7.0f, -8.0f);
    __hv_add_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_varread_f(&_c->sVarf_gGFUT, VOf(Bf0));
    __hv_mul_f(VIf(ZERO), VIf(Bf0), VOf(Bf0));
    __hv_varread_f(&_c->sVarf_KRwMf, VOf(Bf2));
    __hv_min_f(VIf(Bf0), VIf(Bf2), VOf(Bf2));
    __hv_zero_f(VOf(Bf0));
    __hv_max_f(VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_sub_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_floor_f(VIf(Bf0), VOf(Bf1));
    __hv_varread_f(&_c->sVarf_xABvP, VOf(Bf2));
    __hv_zero_f(VOf(Bf3));
    __hv_lt_f(VIf(Bf1), VIf(Bf3), VOf(Bf3));
    __hv_and_f(VIf(Bf2), VIf(Bf3), VOf(Bf3));
    __hv_add_f(VIf(Bf1), VIf(Bf3), VOf(Bf3));
    __hv_cast_fi(VIf(Bf3), VOi(Bi0));
    __hv_var_k_i(VOi(Bi1), 1, 1, 1, 1, 1, 1, 1, 1);
    __hv_add_i(VIi(Bi0), VIi(Bi1), VOi(Bi1));
    __hv_tabread_if(&_c->sTabread_fpV6w, VIi(Bi1), VOf(Bf3));
    __hv_tabread_if(&_c->sTabread_3wyaX, VIi(Bi0), VOf(Bf2));
    __hv_sub_f(VIf(Bf3), VIf(Bf2), VOf(Bf3));
    __hv_sub_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_fma_f(VIf(Bf3), VIf(Bf1), VIf(Bf2), VOf(Bf2));
    __hv_varread_f(&_c->sVarf_Km8h8, VOf(Bf1));
    __hv_mul_f(VIf(Bf2), VIf(Bf1), VOf(Bf1));
    __hv_varread_f(&_c->sVarf_wEdqT, VOf(Bf3));
    __hv_varread_f(&_c->sVarf_vu7ud, VOf(Bf0));
    __hv_mul_f(VIf(Bf3), VIf(Bf0), VOf(Bf0));
    __hv_add_f(VIf(Bf1), VIf(Bf0), VOf(Bf3));
    sEnv_process(Base(_c), &_c->sEnv_s7bY4, VIf(Bf3), &sEnv_s7bY4_sendMessage);
    __hv_varread_i(&_c->sVari_eKbc2, VOi(Bi0));
    __hv_var_k_i(VOi(Bi1), 16807, 16807, 16807, 16807, 16807, 16807, 16807, 16807);
    __hv_mul_i(VIi(Bi0), VIi(Bi1), VOi(Bi1));
    __hv_varwrite_i(&_c->sVari_eKbc2, VIi(Bi1));
    __hv_cast_if(VIi(Bi1), VOf(Bf3));
    __hv_var_k_f(VOf(Bf4), 4.65661e-10f, 4.65661e-10f, 4.65661e-10f, 4.65661e-10f, 4.65661e-10f, 4.65661e-10f, 4.65661e-10f, 4.65661e-10f);
    __hv_mul_f(VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_sample_f(Base(_c), &_c->sSample_AvCvp, VIf(Bf4), &sSample_AvCvp_sendMessage);
    __hv_phasor_k_f(&_c->sPhasor_YEUi9, VOf(Bf4));
    __hv_neg_f(VIf(Bf4), VOf(Bf3));
    __hv_var_k_f(VOf(Bf5), 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
    __hv_add_f(VIf(Bf3), VIf(Bf5), VOf(Bf5));
    __hv_varread_f(&_c->sVarf_QtaNJ, VOf(Bf3));
    __hv_del1_f(&_c->sDel1_aqZsP, VIf(Bf4), VOf(Bf6));
    __hv_lt_f(VIf(Bf4), VIf(Bf6), VOf(Bf6));
    __hv_samphold_f(&_c->sSamphold_muJf8, VIf(Bf3), VIf(Bf6), VOf(Bf6));
    __hv_mul_f(VIf(Bf5), VIf(Bf6), VOf(Bf6));
    __hv_tabhead_f(&_c->sTabhead_Is7NT, VOf(Bf5));
    __hv_var_k_f_r(VOf(Bf3), -1.0f, -2.0f, -3.0f, -4.0f, -5.0f, -6.0f, -7.0f, -8.0f);
    __hv_add_f(VIf(Bf5), VIf(Bf3), VOf(Bf3));
    __hv_varread_f(&_c->sVarf_YAYce, VOf(Bf5));
    __hv_mul_f(VIf(Bf6), VIf(Bf5), VOf(Bf5));
    __hv_varread_f(&_c->sVarf_AMGmd, VOf(Bf6));
    __hv_min_f(VIf(Bf5), VIf(Bf6), VOf(Bf6));
    __hv_zero_f(VOf(Bf5));
    __hv_max_f(VIf(Bf6), VIf(Bf5), VOf(Bf5));
    __hv_sub_f(VIf(Bf3), VIf(Bf5), VOf(Bf5));
    __hv_floor_f(VIf(Bf5), VOf(Bf3));
    __hv_varread_f(&_c->sVarf_XKa0f, VOf(Bf6));
    __hv_zero_f(VOf(Bf7));
    __hv_lt_f(VIf(Bf3), VIf(Bf7), VOf(Bf7));
    __hv_and_f(VIf(Bf6), VIf(Bf7), VOf(Bf7));
    __hv_add_f(VIf(Bf3), VIf(Bf7), VOf(Bf7));
    __hv_cast_fi(VIf(Bf7), VOi(Bi1));
    __hv_var_k_i(VOi(Bi0), 1, 1, 1, 1, 1, 1, 1, 1);
    __hv_add_i(VIi(Bi1), VIi(Bi0), VOi(Bi0));
    __hv_tabread_if(&_c->sTabread_tWIk8, VIi(Bi0), VOf(Bf7));
    __hv_tabread_if(&_c->sTabread_4ceK8, VIi(Bi1), VOf(Bf6));
    __hv_sub_f(VIf(Bf7), VIf(Bf6), VOf(Bf7));
    __hv_sub_f(VIf(Bf5), VIf(Bf3), VOf(Bf3));
    __hv_fma_f(VIf(Bf7), VIf(Bf3), VIf(Bf6), VOf(Bf6));
    __hv_var_k_f(VOf(Bf3), 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
    __hv_floor_f(VIf(Bf4), VOf(Bf7));
    __hv_sub_f(VIf(Bf4), VIf(Bf7), VOf(Bf7));
    __hv_var_k_f(VOf(Bf5), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
    __hv_sub_f(VIf(Bf7), VIf(Bf5), VOf(Bf5));
    __hv_abs_f(VIf(Bf5), VOf(Bf5));
    __hv_var_k_f(VOf(Bf7), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f);
    __hv_sub_f(VIf(Bf5), VIf(Bf7), VOf(Bf7));
    __hv_var_k_f(VOf(Bf5), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f);
    __hv_mul_f(VIf(Bf7), VIf(Bf5), VOf(Bf5));
    __hv_mul_f(VIf(Bf5), VIf(Bf5), VOf(Bf7));
    __hv_mul_f(VIf(Bf5), VIf(Bf7), VOf(Bf8));
    __hv_mul_f(VIf(Bf8), VIf(Bf7), VOf(Bf7));
    __hv_var_k_f(VOf(Bf9), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f);
    __hv_var_k_f(VOf(Bf10), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f);
    __hv_mul_f(VIf(Bf8), VIf(Bf10), VOf(Bf10));
    __hv_sub_f(VIf(Bf5), VIf(Bf10), VOf(Bf10));
    __hv_fma_f(VIf(Bf7), VIf(Bf9), VIf(Bf10), VOf(Bf10));
    __hv_sub_f(VIf(Bf3), VIf(Bf10), VOf(Bf10));
    __hv_var_k_f(VOf(Bf3), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
    __hv_mul_f(VIf(Bf10), VIf(Bf3), VOf(Bf3));
    __hv_mul_f(VIf(Bf6), VIf(Bf3), VOf(Bf3));
    __hv_var_k_f(VOf(Bf6), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
    __hv_add_f(VIf(Bf4), VIf(Bf6), VOf(Bf6));
    __hv_floor_f(VIf(Bf6), VOf(Bf4));
    __hv_sub_f(VIf(Bf6), VIf(Bf4), VOf(Bf4));
    __hv_neg_f(VIf(Bf4), VOf(Bf6));
    __hv_var_k_f(VOf(Bf10), 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
    __hv_add_f(VIf(Bf6), VIf(Bf10), VOf(Bf10));
    __hv_varread_f(&_c->sVarf_Ag72Y, VOf(Bf6));
    __hv_del1_f(&_c->sDel1_rL8gP, VIf(Bf4), VOf(Bf9));
    __hv_lt_f(VIf(Bf4), VIf(Bf9), VOf(Bf9));
    __hv_samphold_f(&_c->sSamphold_q1Nbj, VIf(Bf6), VIf(Bf9), VOf(Bf9));
    __hv_mul_f(VIf(Bf10), VIf(Bf9), VOf(Bf9));
    __hv_tabhead_f(&_c->sTabhead_80SR0, VOf(Bf10));
    __hv_var_k_f_r(VOf(Bf6), -1.0f, -2.0f, -3.0f, -4.0f, -5.0f, -6.0f, -7.0f, -8.0f);
    __hv_add_f(VIf(Bf10), VIf(Bf6), VOf(Bf6));
    __hv_varread_f(&_c->sVarf_MlZog, VOf(Bf10));
    __hv_mul_f(VIf(Bf9), VIf(Bf10), VOf(Bf10));
    __hv_varread_f(&_c->sVarf_S6eRd, VOf(Bf9));
    __hv_min_f(VIf(Bf10), VIf(Bf9), VOf(Bf9));
    __hv_zero_f(VOf(Bf10));
    __hv_max_f(VIf(Bf9), VIf(Bf10), VOf(Bf10));
    __hv_sub_f(VIf(Bf6), VIf(Bf10), VOf(Bf10));
    __hv_floor_f(VIf(Bf10), VOf(Bf6));
    __hv_varread_f(&_c->sVarf_dkjNR, VOf(Bf9));
    __hv_zero_f(VOf(Bf7));
    __hv_lt_f(VIf(Bf6), VIf(Bf7), VOf(Bf7));
    __hv_and_f(VIf(Bf9), VIf(Bf7), VOf(Bf7));
    __hv_add_f(VIf(Bf6), VIf(Bf7), VOf(Bf7));
    __hv_cast_fi(VIf(Bf7), VOi(Bi1));
    __hv_var_k_i(VOi(Bi0), 1, 1, 1, 1, 1, 1, 1, 1);
    __hv_add_i(VIi(Bi1), VIi(Bi0), VOi(Bi0));
    __hv_tabread_if(&_c->sTabread_bGNc4, VIi(Bi0), VOf(Bf7));
    __hv_tabread_if(&_c->sTabread_GcFjQ, VIi(Bi1), VOf(Bf9));
    __hv_sub_f(VIf(Bf7), VIf(Bf9), VOf(Bf7));
    __hv_sub_f(VIf(Bf10), VIf(Bf6), VOf(Bf6));
    __hv_fma_f(VIf(Bf7), VIf(Bf6), VIf(Bf9), VOf(Bf9));
    __hv_var_k_f(VOf(Bf6), 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f);
    __hv_floor_f(VIf(Bf4), VOf(Bf7));
    __hv_sub_f(VIf(Bf4), VIf(Bf7), VOf(Bf7));
    __hv_var_k_f(VOf(Bf4), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
    __hv_sub_f(VIf(Bf7), VIf(Bf4), VOf(Bf4));
    __hv_abs_f(VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf7), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f);
    __hv_sub_f(VIf(Bf4), VIf(Bf7), VOf(Bf7));
    __hv_var_k_f(VOf(Bf4), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f);
    __hv_mul_f(VIf(Bf7), VIf(Bf4), VOf(Bf4));
    __hv_mul_f(VIf(Bf4), VIf(Bf4), VOf(Bf7));
    __hv_mul_f(VIf(Bf4), VIf(Bf7), VOf(Bf10));
    __hv_mul_f(VIf(Bf10), VIf(Bf7), VOf(Bf7));
    __hv_var_k_f(VOf(Bf5), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f);
    __hv_var_k_f(VOf(Bf8), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f);
    __hv_mul_f(VIf(Bf10), VIf(Bf8), VOf(Bf8));
    __hv_sub_f(VIf(Bf4), VIf(Bf8), VOf(Bf8));
    __hv_fma_f(VIf(Bf7), VIf(Bf5), VIf(Bf8), VOf(Bf8));
    __hv_sub_f(VIf(Bf6), VIf(Bf8), VOf(Bf8));
    __hv_var_k_f(VOf(Bf6), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
    __hv_mul_f(VIf(Bf8), VIf(Bf6), VOf(Bf6));
    __hv_mul_f(VIf(Bf9), VIf(Bf6), VOf(Bf6));
    __hv_add_f(VIf(Bf3), VIf(Bf6), VOf(Bf9));
    __hv_varread_f(&_c->sVarf_DTI7M, VOf(Bf8));
    __hv_varread_f(&_c->sVarf_wEdqT, VOf(Bf5));
    __hv_fma_f(VIf(Bf9), VIf(Bf8), VIf(Bf5), VOf(Bf5));
    __hv_tabwrite_f(&_c->sTabwrite_JGG4s, VIf(Bf5));
    __hv_varread_f(&_c->sVarf_ZP6wX, VOf(Bf5));
    __hv_varread_f(&_c->sVarf_WOTlu, VOf(Bf8));
    __hv_fma_f(VIf(Bf2), VIf(Bf5), VIf(Bf8), VOf(Bf8));
    __hv_tabwrite_f(&_c->sTabwrite_3Q7Hv, VIf(Bf8));
    __hv_add_f(VIf(I0), VIf(I1), VOf(Bf8));
    __hv_varread_f(&_c->sVarf_EhxvV, VOf(Bf5));
    __hv_phasor_k_f(&_c->sPhasor_ovvF6, VOf(Bf2));
    __hv_var_k_f(VOf(Bf9), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
    __hv_sub_f(VIf(Bf2), VIf(Bf9), VOf(Bf9));
    __hv_abs_f(VIf(Bf9), VOf(Bf9));
    __hv_var_k_f(VOf(Bf2), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f);
    __hv_sub_f(VIf(Bf9), VIf(Bf2), VOf(Bf2));
    __hv_var_k_f(VOf(Bf9), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f);
    __hv_mul_f(VIf(Bf2), VIf(Bf9), VOf(Bf9));
    __hv_mul_f(VIf(Bf9), VIf(Bf9), VOf(Bf2));
    __hv_mul_f(VIf(Bf9), VIf(Bf2), VOf(Bf7));
    __hv_mul_f(VIf(Bf7), VIf(Bf2), VOf(Bf2));
    __hv_var_k_f(VOf(Bf4), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f);
    __hv_var_k_f(VOf(Bf10), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f);
    __hv_mul_f(VIf(Bf7), VIf(Bf10), VOf(Bf10));
    __hv_sub_f(VIf(Bf9), VIf(Bf10), VOf(Bf10));
    __hv_fma_f(VIf(Bf2), VIf(Bf4), VIf(Bf10), VOf(Bf10));
    __hv_sample_f(Base(_c), &_c->sSample_MLbfG, VIf(Bf10), &sSample_MLbfG_sendMessage);
    __hv_phasor_k_f(&_c->sPhasor_IlhaM, VOf(Bf10));
    __hv_varread_f(&_c->sVarf_oCVD3, VOf(Bf4));
    __hv_mul_f(VIf(Bf10), VIf(Bf4), VOf(Bf4));
    __hv_varread_f(&_c->sVarf_ry7CS, VOf(Bf10));
    __hv_mul_f(VIf(Bf4), VIf(Bf10), VOf(Bf10));
    __hv_fma_f(VIf(Bf8), VIf(Bf5), VIf(Bf10), VOf(Bf10));
    __hv_varwrite_f(&_c->sVarf_wEdqT, VIf(Bf10));
    __hv_add_f(VIf(Bf6), VIf(Bf3), VOf(Bf3));
    __hv_varwrite_f(&_c->sVarf_WOTlu, VIf(Bf3));
    __hv_add_f(VIf(Bf1), VIf(Bf0), VOf(Bf3));
    __hv_add_f(VIf(Bf3), VIf(O0), VOf(O0));
    __hv_add_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(O1), VOf(O1));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
    __hv_store_f(outputBuffers[1]+n, VIf(O1));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

HV_EXPORT int hv_SynthTest2_process_inline(Hv_SynthTest2 *c, float *inputBuffers, float *outputBuffers, int n4) {
  hv_assert(c != NULL);
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD

  // define the heavy input buffer for 2 channel(s)
  float **const bIn = (float **) hv_alloca(2*sizeof(float *));
  bIn[0] = inputBuffers+(0*n4);
  bIn[1] = inputBuffers+(1*n4);

  // define the heavy output buffer for 2 channel(s)
  float **const bOut = (float **) hv_alloca(2*sizeof(float *));
  bOut[0] = outputBuffers+(0*n4);
  bOut[1] = outputBuffers+(1*n4);

  int n = hv_SynthTest2_process(c, bIn, bOut, n4);
  return n;
}

HV_EXPORT int hv_SynthTest2_process_interleaved(Hv_SynthTest2 *c, float *inputBuffers, float *outputBuffers, int n4) {
  hv_assert(c != NULL);
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD

  // define the heavy input buffer for 2 channel(s), uninterleave
  float *const bIn = (float *) hv_alloca(2*n4*sizeof(float));
  #if HV_SIMD_SSE
  for (int i = 0, j = 0; j < n4; j += 4, i += 8) {
    __m128 a = _mm_load_ps(inputBuffers+i);                // LRLR
    __m128 b = _mm_load_ps(inputBuffers+4+i);              // LRLR
    __m128 x = _mm_shuffle_ps(a, b, _MM_SHUFFLE(2,0,2,0)); // LLLL
    __m128 y = _mm_shuffle_ps(a, b, _MM_SHUFFLE(3,1,3,1)); // RRRR
    _mm_stream_ps(bIn+j, x);
    _mm_stream_ps(bIn+n4+j, y);
  }
  _mm_sfence();
  #elif HV_SIMD_NEON
  for (int i = 0, j = 0; j < n4; j += 4, i += 8) {
    float32x4x2_t a = vld2q_f32(inputBuffers+i); // load and uninterleave
    vst1q_f32(bIn+j, a.val[0]);
    vst1q_f32(bIn+n4+j, a.val[1]);
  }
  #else // HV_SIMD_NONE
  for (int j = 0; j < n4; ++j) {
    bIn[0*n4+j] = inputBuffers[0+2*j];
    bIn[1*n4+j] = inputBuffers[1+2*j];
  }
  #endif

  // define the heavy output buffer for 2 channel(s)
  float *const bOut = (float *) hv_alloca(2*n4*sizeof(float));

  int n = hv_SynthTest2_process_inline(c, bIn, bOut, n4);

  // interleave the heavy output into the output buffer
  #if HV_SIMD_SSE
  for (int i = 0, j = 0; j < n4; j += 4, i += 8) {
    __m128 x = _mm_load_ps(bOut+j);                        // LLLL
    __m128 y = _mm_load_ps(bOut+n4+j);                     // RRRR
    __m128 a = _mm_shuffle_ps(x, y, _MM_SHUFFLE(1,0,1,0)); // LLRR
    __m128 b = _mm_shuffle_ps(x, y, _MM_SHUFFLE(3,2,3,2)); // LLRR
    a = _mm_shuffle_ps(a, a, _MM_SHUFFLE(3,1,2,0));        // LRLR
    b = _mm_shuffle_ps(b, b, _MM_SHUFFLE(3,1,2,0));        // LRLR
    _mm_stream_ps(outputBuffers+i, a);
    _mm_stream_ps(outputBuffers+4+i, b);
  }
  _mm_sfence();
  #elif HV_SIMD_NEON
  // https://community.arm.com/groups/processors/blog/2012/03/13/coding-for-neon--part-5-rearranging-vectors
  for (int i = 0, j = 0; j < n4; j += 4, i += 8) {
    float32x4_t x = vld1q_f32(bOut+j);
    float32x4_t y = vld1q_f32(bOut+n4+j);
    float32x4x2_t z = {x, y};
    vst2q_f32(outputBuffers+i, z); // interleave and store
  }
  #else // HV_SIMD_NONE
  for (int i = 0; i < 2; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+2*j] = bOut[i*n4+j];
    }
  }
  #endif

  return n;
}

HV_EXPORT int hv_SynthTest2_process_interleaved_short(Hv_SynthTest2 *c, short *inputBuffers, short *outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = ((float) inputBuffers[i+numChannels*j]) * 0.00003051757813f;
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_SynthTest2_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = (short) (bOut[i*n4+j] * 32767.0f);
    }
  }

  return n;
}
#ifdef __cplusplus
}
#endif
